### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by jzecca** [antonfisher/electron-aspect-ratio-browser-window#1]
Just found your lib and it's working great 👍 

I just had an issue since I'm using TypeScript and this package does not contain definitions.
I'm no TS expert (first time I ever write a definition), but I got it working using the following:

```ts
declare module 'electron-aspect-ratio-browser-window' {
    import { BrowserWindow } from 'electron';

    export default class AspectRatioBrowserWindow extends BrowserWindow {};
}
```

Hope it helps!

**Comment by antonfisher** [comment]
Thanks @jzecca, just published new version with typings: https://www.npmjs.com/package/electron-aspect-ratio-browser-window/v/1.0.2
